apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: my-gcp-project
      auth:
        workloadIdentity:
          serviceAccountEmail: k8s-secrets-reader@my-gcp-project.iam.gserviceaccount.com
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account-key
  namespace: external-secrets
type: Opaque
stringData:
  sa.json: |
    {
      "type": "service_account",
      "project_id": "my-gcp-project",
      "private_key_id": "...",
      "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
      "client_email": "k8s-secrets-reader@my-gcp-project.iam.gserviceaccount.com"
    }
