-- 添加BE节点
ALTER SYSTEM ADD BACKEND 'be_host1:9050';
ALTER SYSTEM ADD BACKEND 'be_host2:9050';
ALTER SYSTEM ADD BACKEND 'be_host3:9050';

-- 添加FE Follower
ALTER SYSTEM ADD FOLLOWER 'fe_host1:9010';
ALTER SYSTEM ADD FOLLOWER 'fe_host2:9010';
ALTER SYSTEM ADD FOLLOWER 'fe_host3:9010';

-- 添加FE Observer
ALTER SYSTEM ADD OBSERVER 'observer_host:9010';

-- 查看集群状态
SHOW FRONTENDS;
SHOW BACKENDS;

-- 下线BE节点
ALTER SYSTEM DECOMMISSION BACKEND 'be_host1:9050';

-- 删除BE节点
ALTER SYSTEM DROP BACKEND 'be_host1:9050';

-- 删除FE节点
ALTER SYSTEM DROP FOLLOWER 'fe_host3:9010';
ALTER SYSTEM DROP OBSERVER 'observer_host:9010';
