# .github/workflows/terraform.yml
name: Terraform Apply

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: my-project-id
        workload_identity_provider: projects/my-project-id/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider
        service_account: terraform@my-project-id.iam.gserviceaccount.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve