apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  namespace: default
  labels:
    app: pvc
    environment: production
spec:
  containers:
  - name: app
    image: nginx:1.25.0
    volumeMounts:
    - name: app-data
      mountPath: /data
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  restartPolicy: Always
  volumes:
  - name: app-data
    persistentVolumeClaim:
      claimName: app-pvc