priority_networks = 192.168.1.0/24

be_port = 9050
webserver_port = 8040
heartbeat_service_port = 9050
brpc_port = 9060

storage_root_path = /opt/apache-doris/be/storage

sys_log_dir = /opt/apache-doris/be/log
log_verbose_modules = *
sys_log_verbose_modules = *
