priority_networks = 192.168.1.0/24

http_port = 8030
rpc_port = 9020
query_port = 9030
edit_log_port = 9010

sys_log_dir = /opt/apache-doris/fe/log
log_verbose_modules = *
sys_log_verbose_modules = *

catalog_try_load_timeout_seconds = 400

max_bdbje_clock_delta_seconds = 5
