apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
type: Opaque
stringData:
  DATABASE_USERNAME: {{ .Values.dbUsername | quote }}
  DATABASE_PASSWORD: {{ .Values.dbPassword | quote }}